---
#
# Playbook to install nagios server, clients and
# generate service checks based on Ansible inventory
#

# we need to collect facts from all hosts we reference
# https://github.com/ansible/ansible/issues/9260
# we skip switches/oobservers because they normally don't
# have python installed.

- hosts: all
  remote_user: "{{ ansible_system_user }}"
  roles:
    - role: sadsfae.ansible-nagios
  tasks: []

# role for nagios clients via NRPE
#- hosts: all:!switches:!oobservers:!nagios:!idrac:!supermicro-6048r:!supermicro-6018r:!supermicro-1028r
#  remote_user: "{{ ansible_system_user }}"
#  roles:
#    - { role: nagios-client }
#    - { role: firewall_client, when: manage_firewall_client }

# role for nagios server
- hosts: all
  remote_user: "{{ ansible_system_user }}"
  roles:
    - { role: nagios }
    - { role: firewall, when: manage_firewall }
    - { role: instructions }
